
get_tweets_with_tweet_id:
	python3 X_Twitter/get_tweets_with_user_context.py

get_tweets_with_bearer_token:
	python3 X_Twitter/get_tweets_with_bearer_token.py

get_user_tweets:
	python3 X_Twitter/user_tweets.py

